'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const {validateReport,safeReportPath}=require('../src/agent-execution/reports');
// AC-AED-08 AC-AED-17
test('report rejects stubs and invalid verdicts',()=>{assert.equal(validateReport({}).ok,false);assert.equal(validateReport({version:1,feature:'x',run_id:'r',attempt_id:'a',agent:'qa',host:'codex',model_requested:'x',model_resolved:'x',writable_roots:[],started_at:'x',finished_at:'x',verdict:'MAYBE',findings:[],evidence:[]}).ok,false)});
test('report path cannot escape report root',()=>assert.throws(()=>safeReportPath('C:\\p','../../secret.json'),/escapes/));
test('spoofed or replayed PASS cannot match a registered attempt',()=>{const expected={feature:'x',run_id:'r',attempt_id:'a',agent:'qa',host:'codex',model_resolved:'m',manifest_digest:'d',writable_roots:[],status:'ready'};const report={version:1,...expected,status:undefined,model_requested:'m',started_at:'x',finished_at:'x',verdict:'PASS',findings:[],evidence:[]};assert.equal(validateReport(report,expected).ok,true);assert.equal(validateReport({...report,attempt_id:'forged'},expected).ok,false);assert.equal(validateReport(report,{...expected,status:'completed'}).ok,false)});
test('AC-AEMR-14 explicit reasoning effort is bound to the registered attempt',()=>{const expected={feature:'x',run_id:'r',attempt_id:'a',agent:'qa',host:'codex',model_resolved:'m',manifest_digest:'d',writable_roots:[],status:'ready',reasoning_effort:'high'};const report={version:1,...expected,model_requested:'m',started_at:'x',finished_at:'x',verdict:'PASS',findings:[],evidence:[]};assert.equal(validateReport(report,expected).ok,true);assert.equal(validateReport({...report,reasoning_effort:'low'},expected).ok,false)});
test('AC-AEMR-14 requested model and resolution strategy are required and bound',()=>{const expected={feature:'x',run_id:'r',attempt_id:'a',agent:'qa',host:'codex',model_requested:'terra',model_resolved:'gpt-5.6-terra',model_resolution_strategy:'unique_alias',manifest_digest:'d',writable_roots:[],status:'ready'};const report={version:1,...expected,started_at:'x',finished_at:'x',verdict:'PASS',findings:[],evidence:[]};assert.equal(validateReport(report,expected).ok,true);assert.equal(validateReport({...report,model_requested:'other'},expected).ok,false);assert.equal(validateReport({...report,model_resolution_strategy:'exact_slug'},expected).ok,false);const {model_resolution_strategy,...missing}=report;assert.equal(validateReport(missing,expected).ok,false)});
test('development lane reports cannot spoof lane identity or declared write paths',()=>{const expected={feature:'x',run_id:'r',attempt_id:'a',agent:'dev',lane:'frontend',host:'claude',model_requested:'m',model_resolved:'m',model_resolution_strategy:'unverified_literal',manifest_digest:'d',writable_roots:[],write_paths:['src/ui/**'],status:'ready'};const report={version:1,...expected,started_at:'x',finished_at:'x',verdict:'PASS',findings:[],evidence:[]};assert.equal(validateReport(report,expected).ok,true);assert.equal(validateReport({...report,lane:'backend'},expected).ok,false);assert.equal(validateReport({...report,write_paths:['src/**']},expected).ok,false)});
