'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const {loadModelCatalog}=require('../src/agent-execution/model-catalog');

async function fixture(value){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'aemr-catalog-'));await fs.writeFile(path.join(dir,'models_cache.json'),typeof value==='string'?value:JSON.stringify(value));return dir}
test('AC-AEMR-03 Codex catalog exposes sanitized models and efforts',async()=>{const dir=await fixture({fetched_at:'2026-07-11',client_version:'0.144.1',models:[{slug:'gpt-5.6-terra',display_name:'GPT-5.6-Terra',supported_reasoning_levels:[{effort:'low'},{effort:'high'}],base_instructions:'must not leak'}]});const r=await loadModelCatalog('codex',{env:{CODEX_HOME:dir},home:'C:\\ignored'});assert.equal(r.available,true);assert.equal(r.source,'codex_local_cache');assert.deepEqual(r.models,[{slug:'gpt-5.6-terra',display_name:'GPT-5.6-Terra',supported_efforts:['low','high']}]);assert.equal(JSON.stringify(r).includes('base_instructions'),false)});
test('AC-AEMR-08 missing, invalid and incompatible caches fail closed',async()=>{const missing=await loadModelCatalog('codex',{env:{CODEX_HOME:path.join(os.tmpdir(),'does-not-exist-aemr')},home:os.homedir()});assert.equal(missing.available,false);assert.equal(missing.reason,'catalog_unavailable');const invalidDir=await fixture('{');assert.equal((await loadModelCatalog('codex',{env:{CODEX_HOME:invalidDir}})).reason,'catalog_invalid');const incompatibleDir=await fixture({models:[{display_name:'No slug'}]});assert.equal((await loadModelCatalog('codex',{env:{CODEX_HOME:incompatibleDir}})).reason,'catalog_incompatible')});
test('AC-AEMR-08 oversized cache is rejected before parsing',async()=>{const dir=await fixture('{}');const r=await loadModelCatalog('codex',{env:{CODEX_HOME:dir},maxBytes:1});assert.equal(r.available,false);assert.equal(r.reason,'catalog_too_large')});
test('security: excessive catalog cardinality is rejected before matching',async()=>{const dir=await fixture({models:[{slug:'gpt-a'},{slug:'gpt-b'}]});const r=await loadModelCatalog('codex',{env:{CODEX_HOME:dir},maxModels:1});assert.equal(r.available,false);assert.equal(r.reason,'catalog_too_many_models')});
test('AC-AEMR-17 manifest data cannot choose a catalog path',async()=>{const dir=await fixture({models:[{slug:'safe-model',display_name:'Safe',supported_reasoning_levels:[]}]});const r=await loadModelCatalog('codex',{env:{CODEX_HOME:dir,AIOSON_MODEL_CATALOG:'C:\\secret.json'},manifest:{catalog_path:'C:\\secret.json'}});assert.equal(r.available,true);assert.equal(r.models[0].slug,'safe-model');assert.equal(Object.hasOwn(r,'path'),false)});
test('hosts without a verified catalog capability stay unsupported',async()=>{const r=await loadModelCatalog('claude',{});assert.equal(r.available,false);assert.equal(r.reason,'unsupported_model_catalog')});
