'use strict';const test=require('node:test');const assert=require('node:assert/strict');const {defaults}=require('../src/agent-execution/manifest');const {normalizeError}=require('../src/agent-execution/adapters/base');
const {applyCapacityPolicy,executeWithCapacityPolicy}=require('../src/agent-execution/dispatcher');
// AC-AED-11 AC-AED-12 AC-AED-13
test('capacity is classified and defaults pause without fallback',()=>{assert.equal(normalizeError(new Error('selected model is at capacity')),'capacity');const m=defaults('x');assert.equal(m.capacity_policy.strategy,'pause');assert.deepEqual(m.agents.qa.fallbacks,[])});
test('capacity fallback uses only explicit ordered pairs and blocks cross-host by default',()=>{const m=defaults('x');m.capacity_policy={strategy:'fallback',max_attempts:3,backoff_ms:0,allow_cross_host:false};m.agents.qa.fallbacks=[{host:'opencode',model:'foreign'},{host:'codex',model:'allowed'}];const r=applyCapacityPolicy(m,m.agents.qa,0);assert.deepEqual(r.sequence,[{host:'codex',model:'allowed'}]);assert.equal(applyCapacityPolicy(m,m.agents.qa,3).reason,'capacity_limit')});
test('effective capacity execution follows explicit fallback order and records resolution',async()=>{const m=defaults('x');m.capacity_policy={strategy:'fallback',max_attempts:2,backoff_ms:0,allow_cross_host:true};delete m.agents.qa.reasoning_effort;m.agents.qa.fallbacks=[{host:'opencode',model:'approved'}];const calls=[];const registry={codex:{execute:async i=>{calls.push(['codex',i.model]);return{ok:false,reason:'capacity'}}},opencode:{execute:async i=>{calls.push(['opencode',i.model]);return{ok:true}}}};const r=await executeWithCapacityPolicy({manifest:m,resolved:m.agents.qa,input:{},adapterRegistry:registry});assert.equal(r.ok,true);assert.deepEqual(calls,[['codex','configured-default'],['opencode','approved']]);assert.equal(r.model,'approved')});
test('capacity retry preserves candidate, applies backoff and stops at the configured limit',async()=>{const m=defaults('x');m.capacity_policy={strategy:'retry',max_attempts:2,backoff_ms:7,allow_cross_host:false};const calls=[];const waits=[];const registry={codex:{execute:async i=>{calls.push(i.model);return{ok:false,reason:'capacity'}}}};const r=await executeWithCapacityPolicy({manifest:m,resolved:m.agents.qa,input:{},adapterRegistry:registry,wait:async ms=>waits.push(ms)});assert.equal(r.reason,'capacity_limit');assert.deepEqual(calls,['configured-default','configured-default']);assert.deepEqual(waits,[7,7]);assert.equal(r.history.length,2)});
test('capacity pause never retries or falls back',async()=>{const m=defaults('x');m.capacity_policy={strategy:'pause',max_attempts:4,backoff_ms:0,allow_cross_host:true};m.agents.qa.fallbacks=[{host:'opencode',model:'forbidden'}];let calls=0;const registry={codex:{execute:async()=>{calls++;return{ok:false,reason:'capacity'}}}};const r=await executeWithCapacityPolicy({manifest:m,resolved:m.agents.qa,input:{},adapterRegistry:registry});assert.equal(r.reason,'capacity');assert.equal(calls,1);assert.equal(r.history.length,1)});
test('capacity execution rejects an adapter host absent from the registry',async()=>{const m=defaults('x');m.agents.qa.host='claude';delete m.agents.qa.reasoning_effort;const r=await executeWithCapacityPolicy({manifest:m,resolved:m.agents.qa,input:{},adapterRegistry:{}});assert.equal(r.reason,'unsupported_host');assert.equal(r.history.length,1);assert.equal(r.history[0].reason,'unsupported_host')});
test('AC-AEMR-13 fallback model is resolved and effort-validated before execution',async()=>{const m=defaults('x');m.capacity_policy={strategy:'fallback',max_attempts:2,backoff_ms:0,allow_cross_host:false};m.agents.qa.model='gpt-5.6-sol';m.agents.qa.reasoning_effort='high';m.agents.qa.fallbacks=[{host:'codex',model:'terra'}];const calls=[];const registry={codex:{execute:async input=>{calls.push([input.model,input.reasoning_effort]);return calls.length===1?{ok:false,reason:'capacity'}:{ok:true}}}};const catalogLoader=async()=>({available:true,source:'fixture',models:[{slug:'gpt-5.6-sol',display_name:'Sol',supported_efforts:['high']},{slug:'gpt-5.6-terra',display_name:'Terra',supported_efforts:['high']}]});const r=await executeWithCapacityPolicy({manifest:m,resolved:m.agents.qa,input:{},adapterRegistry:registry,catalogLoader});assert.equal(r.ok,true);assert.deepEqual(calls,[['gpt-5.6-sol','high'],['gpt-5.6-terra','high']]);assert.equal(r.model,'gpt-5.6-terra')});
test('cross-host fallback drops the inherited reasoning effort instead of dying on unsupported_reasoning_effort',async()=>{const m=defaults('x');m.capacity_policy={strategy:'fallback',max_attempts:2,backoff_ms:0,allow_cross_host:true};m.agents.qa.fallbacks=[{host:'opencode',model:'approved'}];const calls=[];const registry={codex:{execute:async i=>{calls.push(['codex',i.model,i.reasoning_effort]);return{ok:false,reason:'capacity'}}},opencode:{execute:async i=>{calls.push(['opencode',i.model,i.reasoning_effort]);return{ok:true}}}};const r=await executeWithCapacityPolicy({manifest:m,resolved:m.agents.qa,input:{},adapterRegistry:registry});assert.equal(r.ok,true);assert.deepEqual(calls,[['codex','configured-default','medium'],['opencode','approved',null]]);assert.equal(r.host,'opencode');assert.equal(r.reasoning_effort,null);assert.equal(r.history[1].reasoning_effort,null)});
test('unavailable CLI falls back only when the manifest explicitly authorizes unavailable',async()=>{const m=defaults('x');m.capacity_policy={strategy:'fallback',max_attempts:2,backoff_ms:0,allow_cross_host:true};m.agents.dev.fallbacks=[{host:'claude',model:'configured-default',on:['unavailable']}];const calls=[];const registry={codex:{execute:async()=>{calls.push('codex');return{ok:false,reason:'executable_not_found'}}},claude:{execute:async()=>{calls.push('claude');return{ok:true}}}};const catalogLoader=async()=>({available:false,reason:'fixture',models:[]});const r=await executeWithCapacityPolicy({manifest:m,resolved:m.agents.dev,input:{},adapterRegistry:registry,catalogLoader});assert.equal(r.ok,true);assert.deepEqual(calls,['codex','claude']);assert.equal(r.host,'claude')});
test('unavailable CLI never silently becomes the current host without an explicit fallback',async()=>{const m=defaults('x');m.capacity_policy={strategy:'fallback',max_attempts:2,backoff_ms:0,allow_cross_host:true};m.agents.dev.fallbacks=[];let otherCalls=0;const registry={codex:{execute:async()=>({ok:false,reason:'executable_not_found'})},claude:{execute:async()=>{otherCalls++;return{ok:true}}}};const r=await executeWithCapacityPolicy({manifest:m,resolved:m.agents.dev,input:{},adapterRegistry:registry,catalogLoader:async()=>({available:false,models:[]})});assert.equal(r.ok,false);assert.equal(r.reason,'executable_not_found');assert.equal(otherCalls,0)});
