'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const {createTelemetryBridge,redact}=require('../src/agent-execution/telemetry-bridge');const {openRuntimeDb,listExecutionEvents}=require('../src/runtime-store');
const c={feature:'bridge',agent:'dev',dispatcher_run_id:'r',attempt_id:'a',host:'codex',model:'m'};
test('AC-04 AC-05 stream is redacted, ordered and bounded',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'bridge-'));const bridge=await createTelemetryBridge(dir,c,{maxEventBytes:64,maxPersistedBytes:128,flushMs:5});bridge.output('stderr','token=super-secret\n');bridge.output('stdout','x'.repeat(500));bridge.close();const {db}=await openRuntimeDb(dir);const rows=listExecutionEvents(db,bridge.run.telemetry_run_id,{limit:100}).events;assert.equal(rows.some(e=>e.safe_summary.includes('super-secret')),false);assert.equal(rows.some(e=>e.event_type==='output_truncated'),true);db.close()});
test('AC-11 redactor removes credential forms',()=>{assert.equal(redact('Authorization: Bearer abc123'), 'Authorization: Bearer [REDACTED]');assert.equal(redact('api_key=secret'), 'api_key=[REDACTED]')});
test('HIGH: secret split across chunks and long secret never persists',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'split-'));const bridge=await createTelemetryBridge(dir,c,{flushMs:1});bridge.output('stderr','token=super-');bridge.output('stderr','secret-value\n');bridge.close();const {db}=await openRuntimeDb(dir);const raw=JSON.stringify(listExecutionEvents(db,bridge.run.telemetry_run_id,{limit:100}));assert.doesNotMatch(raw,/super-secret-value/);assert.match(raw,/REDACTED/);db.close()});
test('HIGH: unterminated oversized line is dropped with bounded memory',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'dos-'));const bridge=await createTelemetryBridge(dir,c,{maxPendingBytes:32});bridge.output('stdout','token='+('x'.repeat(10000)));bridge.close();const {db}=await openRuntimeDb(dir);const raw=JSON.stringify(listExecutionEvents(db,bridge.run.telemetry_run_id,{limit:100}));assert.doesNotMatch(raw,/x{20}/);assert.match(raw,/output_truncated/);db.close()});
test('AC-AEMR-14 bridge preserves resolution metadata without catalog payloads',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'aemr-bridge-'));const bridge=await createTelemetryBridge(dir,{...c,model:'gpt-5.6-terra',model_requested:'terra',model_resolved:'gpt-5.6-terra',reasoning_effort:'high',model_resolution_strategy:'unique_alias',catalog_source:'codex_local_cache'});assert.equal(bridge.run.model_requested,'terra');assert.equal(bridge.run.model_resolved,'gpt-5.6-terra');assert.equal(bridge.run.reasoning_effort,'high');assert.equal(Object.hasOwn(bridge.run,'catalog_payload'),false);bridge.close()});
