'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');const path=require('node:path');
const {defaults,initManifest,loadManifest,mergeAdditive}=require('../src/agent-execution/manifest');const {validateManifest}=require('../src/agent-execution/schema');
// AC-AED-01 AC-AED-02 AC-AED-03 AC-AED-13 AC-AED-15
test('manifest defaults contain five executable external agents',()=>{const m=defaults('demo','codex');assert.equal(validateManifest(m,'demo').ok,true);assert.equal(Object.keys(m.agents).length,5);assert.equal(m.agents.dev.model,'configured-default');assert.ok(Object.values(m.agents).every(agent=>agent.mode==='external'))});
test('validation reports actionable JSON paths',()=>{const m=defaults('demo');m.host='invalid';m.agents.qa.model='';const r=validateManifest(m,'demo');assert.equal(r.ok,false);assert.deepEqual(r.errors.map(e=>e.path),['$.host','$.agents.qa.model'])});
test('security: model names and fallback names are length bounded before resolution',()=>{const m=defaults('demo');m.agents.dev.model='x'.repeat(201);m.agents.qa.fallbacks=[{host:'codex',model:'y'.repeat(201)}];const r=validateManifest(m,'demo');assert.equal(r.ok,false);assert.ok(r.errors.some(e=>e.path==='$.agents.dev.model'));assert.ok(r.errors.some(e=>e.path==='$.agents.qa.fallbacks[0].model'))});
test('additive initialization preserves operator model',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'aed-'));await initManifest(dir,'demo','codex');const file=path.join(dir,'.aioson/context/agent-execution-demo.json');const m=JSON.parse(await fs.readFile(file));m.agents.dev.model='gpt-custom';await fs.writeFile(file,JSON.stringify(m));await initManifest(dir,'demo','codex');assert.equal((await loadManifest(dir,'demo')).manifest.agents.dev.model,'gpt-custom')});
test('merge additive adds defaults without replacing choices',()=>assert.deepEqual(mergeAdditive({a:{x:2}},{a:{x:1,y:3}}),{a:{x:2,y:3}}));
// AC-AEMR-01 AC-AEMR-02
test('reasoning effort is optional, validated and preserved by additive init',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'aemr-'));const made=await initManifest(dir,'demo','codex');assert.equal(Object.hasOwn(made.manifest.agents.dev,'reasoning_effort'),false);made.manifest.agents.dev.reasoning_effort='high';await fs.writeFile(made.path,JSON.stringify(made.manifest));await initManifest(dir,'demo','codex');const loaded=await loadManifest(dir,'demo');assert.equal(loaded.ok,true);assert.equal(loaded.manifest.agents.dev.reasoning_effort,'high');loaded.manifest.agents.dev.reasoning_effort='extreme';const invalid=validateManifest(loaded.manifest,'demo');assert.ok(invalid.errors.some(error=>error.path==='$.agents.dev.reasoning_effort'))});
// AC-AED-14
test('missing manifest reports legacy compatibility instead of invalid config',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'aed-legacy-'));const loaded=await loadManifest(dir,'legacy');assert.equal(loaded.ok,true);assert.equal(loaded.exists,false);assert.equal(loaded.legacy,true)});
