'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const os=require('node:os');
const {openRuntimeDb,createExecutionRun,findExecutionRun,attachExecutionProcess,transitionExecutionRun,appendExecutionEvent,attachExecutionReport,getExecutionSnapshot,listExecutionEvents,pruneExecutionTelemetry}=require('../src/runtime-store');
async function fixture(){const dir=await fs.mkdtemp(`${os.tmpdir()}${require('node:path').sep}aex-`);const opened=await openRuntimeDb(dir);return{dir,...opened}}
const correlation={feature:'telemetry-demo',agent:'dev',dispatcher_run_id:'run-1',attempt_id:'attempt-1',host:'codex',model:'gpt'};
test('AC-01 AC-02 creates idempotent correlated run and attaches process',async()=>{const {db}=await fixture();const a=createExecutionRun(db,correlation),b=createExecutionRun(db,correlation);assert.equal(a.telemetry_run_id,b.telemetry_run_id);const running=attachExecutionProcess(db,correlation,{pid:123,fingerprint:'fp'});assert.equal(running.state,'running');assert.equal(running.pid,123);db.close()});
test('AC-03 state transitions are monotonic and idempotent',async()=>{const {db}=await fixture();createExecutionRun(db,correlation);transitionExecutionRun(db,correlation,'running');transitionExecutionRun(db,correlation,'waiting_report');const passed=transitionExecutionRun(db,correlation,'passed');assert.equal(transitionExecutionRun(db,correlation,'passed').state,'passed');assert.throws(()=>transitionExecutionRun(db,correlation,'running'),/transition_invalid/);db.close()});
test('AC-08 report requires strong binding',async()=>{const {db}=await fixture();createExecutionRun(db,correlation);assert.throws(()=>attachExecutionReport(db,correlation,{run_id:'wrong',attempt_id:'attempt-1'}),/binding_invalid/);attachExecutionReport(db,correlation,{run_id:'run-1',attempt_id:'attempt-1',path:'report.json',digest:'abc'});assert.equal(findExecutionRun(db,correlation).report_digest,'abc');db.close()});
test('AC-09 cursor reads ordered bounded events and snapshot filters',async()=>{const {db}=await fixture();const run=createExecutionRun(db,correlation);appendExecutionEvent(db,correlation,{type:'diagnostic',safe_summary:'one'});appendExecutionEvent(db,correlation,{type:'diagnostic',safe_summary:'two'});const page=listExecutionEvents(db,run.telemetry_run_id,{after:1,limit:1});assert.equal(page.events.length,1);assert.equal(page.next_cursor,2);assert.equal(getExecutionSnapshot(db,{feature:'telemetry-demo'}).length,1);db.close()});
// aioson-secret: fixture
test('HIGH: payload and reason are recursively redacted and bounded',async()=>{const {db}=await fixture();const run=createExecutionRun(db,correlation);appendExecutionEvent(db,correlation,{type:'diagnostic',safe_summary:'token=abc',payload:{nested:{password:'password=secret',huge:'x'.repeat(50000)}}});transitionExecutionRun(db,correlation,'paused','api_key=secret');const raw=JSON.stringify(listExecutionEvents(db,run.telemetry_run_id,{limit:10}));assert.doesNotMatch(raw,/secret|token=abc/);assert.ok(raw.length<25000);assert.doesNotMatch(findExecutionRun(db,correlation).reason,/secret/);db.close()});
test('MEDIUM: bounded retention removes stale paused runs',async()=>{const {db}=await fixture();createExecutionRun(db,correlation);transitionExecutionRun(db,correlation,'paused','old');db.prepare("UPDATE agent_execution_runs SET updated_at='2000-01-01T00:00:00Z'").run();assert.equal(pruneExecutionTelemetry(db,{retentionDays:1,batch:10}),1);assert.equal(findExecutionRun(db,correlation),null);db.close()});
test('AC-AEMR-14 telemetry stores sanitized model resolution metadata in additive columns',async()=>{const {db}=await fixture();const run=createExecutionRun(db,{...correlation,model:'gpt-5.6-terra',model_requested:'GPT 5.6 Terra',model_resolved:'gpt-5.6-terra',reasoning_effort:'high',model_resolution_strategy:'normalized_name',catalog_source:'codex_local_cache'});assert.equal(run.model,'gpt-5.6-terra');assert.equal(run.model_requested,'GPT 5.6 Terra');assert.equal(run.model_resolved,'gpt-5.6-terra');assert.equal(run.reasoning_effort,'high');assert.equal(run.model_resolution_strategy,'normalized_name');assert.equal(run.catalog_source,'codex_local_cache');db.close()});
test('process re-attach requires explicit replace and records the superseded pid',async()=>{const {db}=await fixture();const run=createExecutionRun(db,correlation);attachExecutionProcess(db,correlation,{pid:111,fingerprint:'fp1'});assert.throws(()=>attachExecutionProcess(db,correlation,{pid:222,fingerprint:'fp2'}),/execution_process_conflict/);const replaced=attachExecutionProcess(db,correlation,{pid:222,fingerprint:'fp2'},{replace:true});assert.equal(replaced.pid,222);assert.equal(replaced.process_fingerprint,'fp2');const events=listExecutionEvents(db,run.telemetry_run_id,{limit:10}).events;assert.ok(events.some(e=>e.event_type==='process_started'&&e.safe_summary.includes('replaces 111')));db.close()});
