'use strict';
const fs=require('node:fs/promises');const path=require('node:path');const crypto=require('node:crypto');
const adapters={claude:require('./adapters/claude'),codex:require('./adapters/codex'),opencode:require('./adapters/opencode')};
const {loadManifest,resolveAgentExecution,resolveExecutionEntry}=require('./manifest');
const {safeReportPath,validateReport}=require('./reports');
const {createTelemetryBridge}=require('./telemetry-bridge');
const TERMINAL=['approved','failed','cancelled'];const LEASE_MS=30000;
function statePath(projectDir,feature){return path.join(projectDir,'.aioson','context',`agent-execution-state-${feature}.json`)}
function leasePath(projectDir,feature){return `${statePath(projectDir,feature)}.lock`}
async function atomic(file,value){await fs.mkdir(path.dirname(file),{recursive:true});const tmp=`${file}.${process.pid}.${crypto.randomUUID()}.tmp`;await fs.writeFile(tmp,`${JSON.stringify(value,null,2)}\n`);await fs.rename(tmp,file)}
async function readState(projectDir,feature){try{return JSON.parse(await fs.readFile(statePath(projectDir,feature),'utf8'))}catch(e){if(e.code==='ENOENT')return null;throw e}}
async function acquireLease(projectDir,feature){const file=leasePath(projectDir,feature);await fs.mkdir(path.dirname(file),{recursive:true});const owner=crypto.randomUUID();for(let pass=0;pass<2;pass++){try{const h=await fs.open(file,'wx');await h.writeFile(JSON.stringify({owner,expires_at:Date.now()+LEASE_MS}));await h.close();return{file,owner}}catch(e){if(e.code!=='EEXIST')throw e;try{const current=JSON.parse(await fs.readFile(file,'utf8'));if(current.expires_at>Date.now())return null;await fs.unlink(file)}catch(readError){if(readError.code!=='ENOENT'&&readError.name!=='SyntaxError')throw readError}}}return null}
async function releaseLease(lease){if(!lease)return;try{const current=JSON.parse(await fs.readFile(lease.file,'utf8'));if(current.owner===lease.owner)await fs.unlink(lease.file)}catch(e){if(e.code!=='ENOENT')throw e}}
async function safePromptPath(projectDir,promptPath){const root=await fs.realpath(projectDir);const candidate=path.resolve(root,promptPath||'.aioson/context/dev-state.md');const real=await fs.realpath(candidate);if(real!==root&&!real.startsWith(root+path.sep))throw new Error('prompt_path escapes project workspace');const stat=await fs.stat(real);if(!stat.isFile())throw new Error('prompt_path must be a regular file');return real}
async function resolveWritableRoots(projectDir,roots=[]){const resolved=[];for(const configured of roots){if(typeof configured!=='string'||!configured.trim())throw new Error('writable_root must be a non-empty path');if(configured.split(/[\\/]+/).includes('..'))throw new Error(`writable_root traversal is forbidden: ${configured}`);const candidate=path.resolve(projectDir,configured);let real;try{real=await fs.realpath(candidate)}catch{throw new Error(`writable_root does not exist: ${configured}`)}if(!(await fs.stat(real)).isDirectory())throw new Error(`writable_root is not a directory: ${configured}`);if(!resolved.includes(real))resolved.push(real)}return resolved}
function capacitySequence(manifest,resolved){const policy=manifest.capacity_policy;if(policy.strategy!=='fallback')return[];return resolved.fallbacks.filter(item=>policy.allow_cross_host===true||item.host===resolved.host)}
function applyCapacityPolicy(manifest,resolved,attemptCount=0){const p=manifest.capacity_policy;if(attemptCount>=p.max_attempts)return{action:'pause',reason:'capacity_limit'};if(p.strategy==='fallback'){const sequence=capacitySequence(manifest,resolved);return sequence.length?{action:'fallback',sequence}:{action:'pause',reason:'no_authorized_fallback'}}if(p.strategy==='retry'||p.strategy==='wait')return{action:p.strategy,backoff_ms:p.backoff_ms};return{action:'pause'}}
async function executeWithCapacityPolicy({manifest,resolved,input,adapterRegistry=adapters,catalogLoader,wait=(ms)=>new Promise(resolve=>setTimeout(resolve,ms))}) {
  const history=[];
  const primary=resolved.ok?resolved:await resolveExecutionEntry(resolved,{catalogLoader});
  if(!primary.ok)return{ok:false,reason:primary.reason,candidates:primary.candidates||[],history};
  const candidates=[primary,...capacitySequence(manifest,resolved).map(item=>({...resolved,ok:false,host:item.host,model:item.model,model_requested:undefined}))];
  let index=0;
  for(let count=0;count<manifest.capacity_policy.max_attempts;count++){
    let candidate=candidates[index];
    if(!candidate.ok){
      candidate=await resolveExecutionEntry(candidate,{catalogLoader});
      candidates[index]=candidate;
      if(!candidate.ok){
        history.push({attempt:count+1,host:candidate.host,model_requested:candidate.model_requested||candidate.model,model:null,reason:candidate.reason});
        return{ok:false,reason:candidate.reason,candidates:candidate.candidates||[],history};
      }
    }
    const adapter=adapterRegistry[candidate.host];
    if(!adapter)return{ok:false,reason:'unsupported_host',history};
    const prompt_text=String(input.prompt_text||'')
      .replace(/host=[^,\n]+/,`host=${candidate.host}`)
      .replace(/model_resolved=[^,\n]+/,`model_resolved=${candidate.model}`)
      .replace(/model_resolution_strategy=[^,\n]+/,`model_resolution_strategy=${candidate.model_resolution_strategy}`);
    const result=await adapter.execute({...input,prompt_text,mode:candidate.mode,model:candidate.model,reasoning_effort:candidate.reasoning_effort});
    history.push({attempt:count+1,host:candidate.host,model_requested:candidate.model_requested,model:candidate.model,model_resolution_strategy:candidate.model_resolution_strategy,reasoning_effort:candidate.reasoning_effort,reason:result.reason||null});
    if(result.ok)return{...result,host:candidate.host,model:candidate.model,model_requested:candidate.model_requested,model_resolution_strategy:candidate.model_resolution_strategy,reasoning_effort:candidate.reasoning_effort,history};
    if(result.reason!=='capacity')return{...result,history};
    const decision=applyCapacityPolicy(manifest,resolved,count);
    if(decision.action==='pause')return{ok:false,reason:decision.reason||'capacity',history};
    if(decision.action==='fallback'){
      if(index+1>=candidates.length)return{ok:false,reason:'fallback_exhausted',history};
      index+=1;
    }else if(decision.action==='wait'||decision.action==='retry'){
      if(decision.backoff_ms)await wait(decision.backoff_ms);
    }
  }
  return{ok:false,reason:'capacity_limit',history};
}
function buildExecutionPrompt(promptText,expected,reportPath){return `${promptText}\n\nAIOSON EXECUTION CONTRACT\nComplete the requested agent work, then write exactly one JSON report to: ${reportPath}\nThe report must include: version=1, feature=${expected.feature}, run_id=${expected.run_id}, attempt_id=${expected.attempt_id}, agent=${expected.agent}, host=${expected.host}, model_requested=${expected.model_requested}, model_resolved=${expected.model_resolved}, model_resolution_strategy=${expected.model_resolution_strategy}, reasoning_effort=${expected.reasoning_effort||'null'}, manifest_digest=${expected.manifest_digest}, writable_roots=${JSON.stringify(expected.writable_roots)}, started_at, finished_at, verdict (PASS|FAIL|BLOCKED), findings[], evidence[]. Do not report PASS unless the work and verification completed.`}
async function readBoundReport(projectDir,relative,expected){const file=safeReportPath(projectDir,relative);let report;try{report=JSON.parse(await fs.readFile(file,'utf8'))}catch(error){return{ok:false,reason:error.code==='ENOENT'?'report_missing':'report_invalid_json',error:error.message}}const validation=validateReport(report,expected);return validation.ok?{ok:true,file,report}:{ok:false,reason:'report_binding_invalid',errors:validation.errors}}
async function dispatch({projectDir,feature,agent='dev',runId,promptPath,adapterRegistry=adapters,catalogLoader,timeout=600000}){
 const lease=await acquireLease(projectDir,feature);if(!lease)return{ok:false,status:'paused',reason:'lease_held',resume_command:`aioson agent:execution:resume . --feature=${feature}`};
 try{const loaded=await loadManifest(projectDir,feature);if(!loaded.exists)return{ok:false,status:'paused',reason:'manifest_missing',resume_command:`aioson agent:execution:resume . --feature=${feature}`};if(!loaded.ok)return{ok:false,status:'paused',reason:'manifest_invalid',errors:loaded.errors};
  if(!loaded.manifest.agents[agent])return{ok:false,status:'paused',reason:'agent_unknown',agent};
  if(loaded.manifest.agents[agent].enabled===false)return{ok:true,status:'skipped',reason:'agent_disabled',feature,agent,idempotent:true};
  let state=await readState(projectDir,feature);if(state&&state.manifest_digest!==loaded.digest&&!TERMINAL.includes(state.status))return{ok:false,status:'paused',reason:'manifest_digest_changed',expected:state.manifest_digest,actual:loaded.digest};if(state?.completed_agents?.includes(agent))return{ok:true,status:state.status,idempotent:true,state};
  let safePrompt;try{safePrompt=await safePromptPath(projectDir,promptPath)}catch(error){return{ok:false,status:'paused',reason:'invalid_prompt_path',error:error.message}}
  const resolved=await resolveAgentExecution(loaded.manifest,agent,{}, {catalogLoader});if(!resolved.ok)return{ok:false,status:'paused',reason:resolved.reason,candidates:resolved.candidates||[],supported:resolved.supported||[]};const adapter=adapterRegistry[resolved.host];const run_id=runId||state?.run_id||crypto.randomUUID();const attempt_id=crypto.randomUUID();if(!adapter)return{ok:false,status:'paused',reason:'unsupported_host'};let writableRoots;try{writableRoots=await resolveWritableRoots(projectDir,resolved.writable_roots)}catch(error){return{ok:false,status:'paused',reason:'invalid_writable_root',error:error.message}}const reportRelative=resolved.report.replace(/\{run_id\}/g,run_id);const reportFile=safeReportPath(projectDir,reportRelative);const expected={feature,run_id,attempt_id,agent,host:resolved.host,model_requested:resolved.model_requested,model_resolved:resolved.model,model_resolution_strategy:resolved.model_resolution_strategy,reasoning_effort:resolved.reasoning_effort,manifest_digest:loaded.digest,writable_roots:writableRoots,status:'running'};const promptText=await fs.readFile(safePrompt,'utf8');const executionInput={mode:resolved.mode,model:resolved.model,reasoning_effort:resolved.reasoning_effort,writable_roots:writableRoots,cwd:projectDir,prompt_text:buildExecutionPrompt(promptText,expected,path.relative(projectDir,reportFile)),timeout};const built=adapter.build(executionInput);
  const correlation={feature,agent,dispatcher_run_id:run_id,attempt_id,host:resolved.host,model:resolved.model,model_requested:resolved.model_requested,model_resolved:resolved.model,reasoning_effort:resolved.reasoning_effort,model_resolution_strategy:resolved.model_resolution_strategy,catalog_source:resolved.catalog_source};const telemetry=await createTelemetryBridge(projectDir,correlation);
  const attempt={...expected,telemetry_run_id:telemetry.run.telemetry_run_id,status:built.ok?'running':'blocked',reason:built.reason||null,report:reportRelative};state={version:1,feature,run_id,manifest_path:path.relative(projectDir,loaded.path),manifest_digest:loaded.digest,status:built.ok?'running':'paused',reason:built.reason||null,attempts:[...(state?.attempts||[]),attempt],completed_agents:state?.completed_agents||[],updated_at:new Date().toISOString()};await atomic(statePath(projectDir,feature),state);if(!built.ok){telemetry.transition('paused',built.reason);telemetry.close();return{ok:false,status:'paused',reason:built.reason,capability:built.capability,resume_command:`aioson agent:execution:resume . --feature=${feature}`,state}};
  Object.assign(executionInput,{onSpawn:(pid,at)=>telemetry.onSpawn(pid,at),onStdout:d=>telemetry.output('stdout',d),onStderr:d=>telemetry.output('stderr',d)});
  const execution=await executeWithCapacityPolicy({manifest:loaded.manifest,resolved,input:executionInput,adapterRegistry,catalogLoader});attempt.execution_history=execution.history||[];for(const item of attempt.execution_history){if(item.attempt>1)telemetry.event(item.host===resolved.host?'retry':'fallback',`${item.host}/${item.model}`,{attempt:item.attempt,reason:item.reason})}attempt.model_resolved=execution.model||resolved.model;attempt.model_resolution_strategy=execution.model_resolution_strategy||resolved.model_resolution_strategy;attempt.reasoning_effort=execution.reasoning_effort||resolved.reasoning_effort;attempt.host_resolved=execution.host||resolved.host;if(!execution.ok){attempt.status='blocked';attempt.reason=execution.reason;state.status='paused';state.reason=execution.reason;state.updated_at=new Date().toISOString();await atomic(statePath(projectDir,feature),state);if(execution.reason==='timeout')telemetry.event('timeout','Execution timeout');telemetry.transition('paused',execution.reason);telemetry.close();return{ok:false,status:'paused',reason:execution.reason,candidates:execution.candidates||[],execution,state,resume_command:`aioson agent:execution:resume . --feature=${feature}`}}
  telemetry.transition('waiting_report');
  const boundExpected={...expected,host:attempt.host_resolved,model_resolved:attempt.model_resolved,model_resolution_strategy:attempt.model_resolution_strategy,reasoning_effort:attempt.reasoning_effort,status:'running'};const reportResult=await readBoundReport(projectDir,reportRelative,boundExpected);if(!reportResult.ok){attempt.status='blocked';attempt.reason=reportResult.reason;state.status='paused';state.reason=reportResult.reason;state.updated_at=new Date().toISOString();await atomic(statePath(projectDir,feature),state);telemetry.transition('paused',reportResult.reason);telemetry.close();return{ok:false,status:'paused',reason:reportResult.reason,report:reportResult,state,resume_command:`aioson agent:execution:resume . --feature=${feature}`}}
  const digest=crypto.createHash('sha256').update(JSON.stringify(reportResult.report)).digest('hex');telemetry.report(reportResult.report,reportRelative,digest);attempt.status='completed';attempt.verdict=reportResult.report.verdict;state.status=reportResult.report.verdict==='PASS'?'verification_planned':'correcting';telemetry.transition(reportResult.report.verdict==='PASS'?'passed':reportResult.report.verdict==='FAIL'?'failed':'correcting');telemetry.close();if(reportResult.report.verdict==='PASS'&&!state.completed_agents.includes(agent))state.completed_agents.push(agent);state.updated_at=new Date().toISOString();await atomic(statePath(projectDir,feature),state);return{ok:true,status:state.status,run_id,attempt_id,execution,report:reportResult.report,state};
 }finally{await releaseLease(lease)}
}
module.exports={acquireLease,applyCapacityPolicy,buildExecutionPrompt,capacitySequence,dispatch,executeWithCapacityPolicy,leasePath,readBoundReport,readState,releaseLease,resolveWritableRoots,safePromptPath,statePath};
