'use strict';

const MANAGED_FILES = [
  'CLAUDE.md',
  'AGENTS.md',
  'OPENCODE.md',
  '.aioson/config.md',
  '.aioson/agents/setup.md',
  '.aioson/agents/discovery-design-doc.md',
  '.aioson/agents/discover.md',
  '.aioson/agents/analyst.md',
  '.aioson/agents/scope-check.md',
  '.aioson/agents/architect.md',
  '.aioson/agents/ux-ui.md',
  '.aioson/agents/product.md',
  '.aioson/agents/deyvin.md',
  '.aioson/agents/pair.md',
  '.aioson/agents/pm.md',
  '.aioson/agents/sheldon.md',
  '.aioson/agents/planner.md',
  '.aioson/agents/dev.md',
  '.aioson/agents/qa.md',
  '.aioson/agents/quality.md',
  '.aioson/docs/quality/engineering.md',
  '.aioson/quality/evals/core.json',
  '.aioson/agents/validator.md',
  '.aioson/agents/tester.md',
  '.aioson/agents/orchestrator.md',
  '.aioson/agents/pentester.md',
  '.aioson/agents/squad.md',
  '.aioson/agents/orache.md',
  '.aioson/agents/genome.md',
  '.aioson/agents/neo.md',
  '.aioson/agents/help.md',
  '.aioson/agents/design-hybrid-forge.md',
  '.aioson/agents/site-forge.md',
  '.aioson/agents/benchmark.md',
  '.aioson/agents/profiler-researcher.md',
  '.aioson/agents/profiler-enricher.md',
  '.aioson/agents/profiler-forge.md',
  '.aioson/agents/committer.md',
  '.aioson/agents/copywriter.md',
  '.aioson/agents/briefing.md',
  '.aioson/agents/refiner.md',
  '.aioson/agents/forge-run.md',
  '.aioson/agents/shakedown.md',
  '.aioson/docs/shakedown/completeness-checklist.md',
  '.aioson/docs/dev/execution-lanes.md',
  '.aioson/docs/planner/orchestrated-execution.md',
  '.aioson/docs/delivery-followups.md',
  '.aioson/docs/squad/package-contract.md',
  '.aioson/docs/squad/creation-flow.md',
  '.aioson/docs/squad/research-loop.md',
  '.aioson/docs/squad/quality-lens.md',
  '.aioson/docs/squad/workflow-quality.md',
  '.aioson/docs/squad/content-output.md',
  '.aioson/docs/squad/session-operations.md',
  '.aioson/docs/squad/genome-bindings.md',
  '.aioson/docs/squad/eval-gate.md',
  '.aioson/docs/genome/generation-flow.md',
  '.aioson/docs/genome/evidence-and-quality.md',
  '.aioson/docs/genome/runtime-application.md',
  '.aioson/docs/genome/legacy-command-contracts.md',
  '.aioson/docs/neo/state-diagnostics.md',
  '.aioson/docs/neo/runtime-storage.md',
  '.aioson/docs/neo/routing-matrix.md',
  '.aioson/docs/neo/agent-catalog.md',
  '.aioson/docs/neo/legacy-routing-reference.md',
  '.aioson/docs/pentester/review-contract-and-findings.md',
  '.aioson/docs/pentester/coverage-standard.md',
  '.aioson/docs/pentester/framework-playbooks.md',
  '.aioson/docs/pentester/correction-cycle.md',
  '.aioson/docs/pentester/app-playbooks.md',
  '.aioson/docs/pentester/browser-dast-playbook.md',
  '.aioson/docs/pentester/llm-supplychain.md',
  '.aioson/docs/pentester/reporting.md',
  '.aioson/docs/pentester/legacy-agent-contract.md',
  '.aioson/docs/copywriter/modes-and-outputs.md',
  '.aioson/docs/copywriter/genomes-and-research.md',
  '.aioson/docs/copywriter/strategy-and-delivery.md',
  '.aioson/docs/copywriter/campaign-package.md',
  '.aioson/docs/copywriter/legacy-agent-contract.md',
  '.aioson/docs/committer/outstanding-work.md',
  '.aioson/docs/briefing/activation-and-intake.md',
  '.aioson/docs/briefing/source-pack-intake.md',
  '.aioson/docs/briefing/sql-as-documentation.md',
  '.aioson/docs/briefing/exploration-and-artifacts.md',
  '.aioson/docs/briefing/refinement-loop.md',
  '.aioson/docs/briefing/review-authority.md',
  '.aioson/docs/briefing/prototype-and-delegation.md',
  '.aioson/docs/briefing/visual-exploration.md',
  '.aioson/docs/briefing/review-surface-fallback.md',
  '.aioson/docs/briefing/legacy-agent-contract.md',
  '.aioson/docs/briefing/legacy-refiner-agent-contract.md',
  '.aioson/docs/orache/investigation-strategy.md',
  '.aioson/docs/orache/dimensions-and-synthesis.md',
  '.aioson/docs/orache/report-and-integration.md',
  '.aioson/docs/orache/legacy-agent-contract.md',
  '.aioson/docs/setup/onboarding-flow.md',
  '.aioson/docs/setup/stack-and-design-reference.md',
  '.aioson/docs/setup/context-and-handoff.md',
  '.aioson/docs/setup/legacy-agent-contract.md',
  '.aioson/docs/profiler/evidence-and-inference.md',
  '.aioson/docs/profiler/trait-and-method-analysis.md',
  '.aioson/docs/profiler/enriched-profile-contract.md',
  '.aioson/docs/profiler/legacy-enricher-agent-contract.md',
  '.aioson/docs/profiler/forge-package-contract.md',
  '.aioson/docs/profiler/advisor-hybrid-and-binding.md',
  '.aioson/docs/profiler/forge-verification.md',
  '.aioson/docs/profiler/legacy-forge-agent-contract.md',
  '.aioson/docs/gateway/agent-routing.md',
  '.aioson/docs/gateway/workflow-runtime.md',
  '.aioson/docs/gateway/process-and-research.md',
  '.aioson/docs/gateway/legacy-agents-entrypoint.md',
  '.aioson/docs/gateway/legacy-claude-entrypoint.md',
  '.aioson/docs/agent-help.md',
  '.aioson/docs/feature-expansion-taxonomy.md',
  '.aioson/docs/feature-completeness-contract.md',
  '.aioson/docs/prototype-contract.md',
  '.aioson/docs/model-delegation.md',
  '.aioson/docs/reference-identity.md',
  '.aioson/docs/web-capture.md',
  '.aioson/docs/benchmark/execution-playbook.md',
  '.aioson/docs/benchmark/traversal.md',
  '.aioson/rules/visual-exploration-contract.md',
  '.aioson/docs/product/conversation-playbook.md',
  '.aioson/docs/product/research-loop.md',
  '.aioson/docs/product/quality-lens.md',
  '.aioson/docs/product/prd-contract.md',
  '.aioson/docs/deyvin/continuity-recovery.md',
  '.aioson/docs/deyvin/pair-execution.md',
  '.aioson/docs/deyvin/runtime-handoffs.md',
  '.aioson/docs/deyvin/debugging-escalation.md',
  '.aioson/docs/feature-continuity-mapping.md',
  '.aioson/docs/handoff-persistence.md',
  '.aioson/docs/integrations/dashboard-app-form-publish-mapping.md',
  '.aioson/docs/play/README.md',
  '.aioson/docs/play/agent-usage-guide.md',
  '.aioson/docs/play/app-compatibility-guide.md',
  '.aioson/docs/play/auth-services-and-testing.md',
  '.aioson/docs/play/llm-data-and-bindings.md',
  '.aioson/docs/play/manifest-and-runtime.md',
  '.aioson/docs/play/source-map.md',
  '.aioson/docs/sheldon/research-loop.md',
  '.aioson/docs/sheldon/web-intelligence.md',
  '.aioson/docs/sheldon/quality-lens.md',
  '.aioson/docs/sheldon/enrichment-paths.md',
  '.aioson/docs/sheldon/harness-contract.md',
  '.aioson/docs/dev/stack-conventions.md',
  '.aioson/docs/dev/execution-discipline.md',
  '.aioson/docs/dev/simple-plan-lane.md',
  '.aioson/docs/quality/code-health-analysis.md',
  '.aioson/docs/quality/code-size-limits.md',
  '.aioson/docs/quality/coupling-limits.md',
  '.aioson/docs/qa/browser-walkthrough.md',
  '.aioson/skills/process/decision-presentation/SKILL.md',
  '.aioson/skills/process/decision-presentation/references/jargon-map.en.yaml',
  '.aioson/skills/process/decision-presentation/references/jargon-map.pt-BR.yaml',
  '.aioson/skills/process/decision-presentation/references/compatibility-and-doctor.md',
  '.aioson/skills/process/prompt-sharpener/SKILL.md',
  '.aioson/skills/process/prompt-sharpener/references/prompt-diagnostics.md',
  '.aioson/skills/process/prompt-sharpener/agents/openai.yaml',
  '.aioson/skills/process/review-intelligence/SKILL.md',
  '.aioson/skills/process/review-intelligence/agents/openai.yaml',
  '.aioson/skills/process/review-intelligence/references/framing.md',
  '.aioson/skills/process/review-intelligence/references/specification.md',
  '.aioson/skills/process/review-intelligence/references/architecture.md',
  '.aioson/skills/process/review-intelligence/references/delivery-assurance.md',
  '.aioson/skills/registry.json',
  '.aioson/skills/process/briefing-expansion-scout/SKILL.md',
  '.aioson/skills/process/product-scope-expansion/SKILL.md',
  '.aioson/skills/process/sheldon-expansion-audit/SKILL.md',
  '.aioson/skills/process/prototype-forge/SKILL.md',
  '.aioson/skills/process/prototype-forge/references/build-contract.md',
  '.aioson/skills/process/prototype-forge/references/quality-and-manifest.md',
  '.aioson/skills/process/design-hybrid-forge/SKILL.md',
  '.aioson/skills/process/design-hybrid-forge/references/pair-compatibility.md',
  '.aioson/skills/process/design-hybrid-forge/references/external-source-ingestion.md',
  '.aioson/skills/process/design-hybrid-forge/references/crossover-protocol.md',
  '.aioson/skills/process/design-hybrid-forge/references/variation-library.md',
  '.aioson/skills/process/design-hybrid-forge/references/naming-registry.md',
  '.aioson/skills/process/design-hybrid-forge/references/output-contract.md',
  '.aioson/skills/process/design-hybrid-forge/references/quality-gates.md',
  '.aioson/skills/process/reference-identity-extract/SKILL.md',
  '.aioson/skills/process/reference-identity-extract/references/extraction-contract.md',
  '.aioson/skills/process/reference-identity-extract/references/identity-schema.md',
  '.aioson/skills/static/laravel-conventions.md',
  '.aioson/skills/static/tall-stack-patterns.md',
  '.aioson/skills/static/jetstream-setup.md',
  '.aioson/skills/static/rails-conventions.md',
  '.aioson/skills/static/node-express-patterns.md',
  '.aioson/skills/static/node-typescript-patterns.md',
  '.aioson/skills/static/nextjs-patterns.md',
  '.aioson/skills/static/ui-ux-modern.md',
  '.aioson/skills/static/landing-page-forge.md',
  '.aioson/skills/static/landing-page-deploy.md',
  '.aioson/skills/marketing/vsl-craft.md',
  '.aioson/skills/marketing/references/one-belief.md',
  '.aioson/skills/marketing/references/five-acts.md',
  '.aioson/skills/marketing/references/fascinations.md',
  '.aioson/skills/marketing/references/offer-structure.md',
  '.aioson/skills/marketing/references/pms-research.md',
  '.aioson/skills/marketing/references/patterns.md',
  '.aioson/skills/marketing/references/anti-patterns.md',
  '.aioson/skills/marketing/references/market-intelligence.md',
  '.aioson/skills/marketing/references/headline-matrix.md',
  '.aioson/skills/marketing/references/cta-matrix.md',
  '.aioson/skills/marketing/references/platform-constraints.md',
  '.aioson/genomes/copywriting.md',
  '.aioson/skills/static/web3-ethereum-patterns.md',
  '.aioson/skills/static/web3-solana-patterns.md',
  '.aioson/skills/static/web3-cardano-patterns.md',
  '.aioson/skills/static/web3-security-checklist.md',
  '.aioson/skills/static/web-research-cache.md',
  '.aioson/skills/static/git-conventions.md',
  '.aioson/skills/design/interface-design/SKILL.md',
  '.aioson/skills/design/interface-design/references/aesthetic-registers.md',
  '.aioson/skills/design/interface-design/references/components-and-states.md',
  '.aioson/skills/design/interface-design/references/design-directions.md',
  '.aioson/skills/design/interface-design/references/handoff-and-quality.md',
  '.aioson/skills/design/interface-design/references/intent-and-domain.md',
  '.aioson/skills/design/interface-design/references/tokens-and-depth.md',
  '.aioson/skills/dynamic/laravel-docs.md',
  '.aioson/skills/dynamic/flux-ui-docs.md',
  '.aioson/skills/dynamic/npm-packages.md',
  '.aioson/skills/dynamic/ethereum-docs.md',
  '.aioson/skills/dynamic/solana-docs.md',
  '.aioson/skills/dynamic/cardano-docs.md',
  '.aioson/mcp/servers.md',
  '.aioson/schemas/genome.schema.json',
  '.aioson/schemas/genome-meta.schema.json',
  '.aioson/schemas/squad-manifest.schema.json',
  '.aioson/schemas/squad-eval-report.schema.json',
  '.aioson/schemas/squad-blueprint.schema.json',
  '.aioson/schemas/readiness.schema.json',
  '.aioson/schemas/content-blueprint.schema.json',
  '.aioson/schemas/review-intelligence.schema.json',
  '.aioson/schemas/genome.schema.json',
  '.aioson/schemas/genome-meta.schema.json',
  '.aioson/tasks/squad-design.md',
  '.aioson/tasks/squad-create.md',
  '.aioson/tasks/squad-validate.md',
  '.aioson/tasks/squad-eval.md',
  '.aioson/tasks/squad-analyze.md',
  '.aioson/tasks/squad-extend.md',
  '.aioson/tasks/squad-export.md',
  '.aioson/tasks/squad-repair.md',
  '.aioson/tasks/squad-pipeline.md',
  '.aioson/tasks/squad-learning-review.md',
  '.aioson/profiler-reports/.gitkeep',
  '.aioson/advisors/.gitkeep',
  '.claude/agents/aioson-researcher.md',
  '.codex/agents/aioson-researcher.toml'
];

const REQUIRED_FILES = [
  'CLAUDE.md',
  'AGENTS.md',
  'OPENCODE.md',
  '.claude/commands/aioson/agent/setup.md',
  '.claude/commands/aioson/agent/discover.md',
  '.claude/commands/aioson/agent/dev.md',
  '.claude/commands/aioson/agent/qa.md',
  '.claude/commands/aioson/agent/quality.md',
  '.aioson/config.md',
  '.aioson/agents/setup.md',
  '.aioson/agents/discovery-design-doc.md',
  '.aioson/agents/discover.md',
  '.aioson/agents/analyst.md',
  '.aioson/agents/ux-ui.md',
  '.aioson/agents/planner.md',
  '.aioson/agents/dev.md',
  '.aioson/context/.gitkeep'
];

const CONTEXT_REQUIRED_FIELDS = [
  'project_name',
  'project_type',
  'profile',
  'framework',
  'framework_installed',
  'classification',
  'aioson_version'
];

const CONTEXT_ALLOWED_CLASSIFICATIONS = ['MICRO', 'SMALL', 'MEDIUM'];
const CONTEXT_ALLOWED_PROJECT_TYPES = ['web_app', 'api', 'site', 'script', 'dapp', 'desktop_app'];
const CONTEXT_ALLOWED_PROFILES = ['developer', 'creator', 'team'];

const AGENT_DEFINITIONS = [
  {
    id: 'setup',
    displayName: 'Setup',
    description: 'Project onboarding and context setup',
    command: '@setup',
    path: '.aioson/agents/setup.md',
    dependsOn: [],
    output: '.aioson/context/project.context.md'
  },
  {
    id: 'discovery-design-doc',
    displayName: 'Discovery/Design Doc',
    description: 'Optional repository-surface discovery for a named implementation unknown',
    command: '@discovery-design-doc',
    path: '.aioson/agents/discovery-design-doc.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: 'bounded repository evidence + optional dossier code-map entry'
  },
  {
    id: 'discover',
    displayName: 'Discover',
    description: 'Semantic knowledge discovery and bootstrap cache generation',
    command: '@discover',
    path: '.aioson/agents/discover.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/context/bootstrap/what-is.md + .aioson/context/bootstrap/how-it-works.md + .aioson/context/bootstrap/what-it-does.md + .aioson/context/bootstrap/current-state.md'
  },
  {
    id: 'product',
    displayName: 'Product',
    description: 'Product vision, PRD and feature scoping',
    command: '@product',
    path: '.aioson/agents/product.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/context/prd.md or .aioson/context/prd-{slug}.md (single product authority)'
  },
  {
    id: 'deyvin',
    displayName: 'Deyvin',
    description: 'Pair programming partner for continuity sessions',
    command: '@deyvin',
    path: '.aioson/agents/deyvin.md',
    aliases: ['pair'],
    dependsOn: ['.aioson/context/project.context.md'],
    output: 'small code changes + continuity notes + runtime logs/tasks'
  },
  {
    id: 'analyst',
    displayName: 'Analyst',
    description: 'Optional evidence-backed analysis of a named ambiguity (all sizes)',
    command: '@analyst',
    path: '.aioson/agents/analyst.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: 'bounded recommendation to Product or Planner + optional dossier entry'
  },
  {
    id: 'scope-check',
    displayName: 'Scope Check',
    description: 'Optional evidence-based review of a named scope-drift concern',
    command: '@scope-check',
    path: '.aioson/agents/scope-check.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/prd.md or .aioson/context/prd-{slug}.md',
      '.aioson/context/implementation-plan.md or .aioson/context/implementation-plan-{slug}.md'
    ],
    output: 'bounded alignment verdict + optional dossier entry'
  },
  {
    id: 'architect',
    displayName: 'Architect',
    description: 'Optional repository-grounded answer to a named technical boundary (all sizes)',
    command: '@architect',
    path: '.aioson/agents/architect.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/prd.md or .aioson/context/prd-{slug}.md',
      '.aioson/context/implementation-plan.md or .aioson/context/implementation-plan-{slug}.md (when present)'
    ],
    output: 'bounded technical decision to Planner or Dev + optional dossier entry'
  },
  {
    id: 'ux-ui',
    displayName: 'UI/UX',
    description: 'Optional prototype-grounded interaction decision (all sizes)',
    command: '@ux-ui',
    path: '.aioson/agents/ux-ui.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/prd.md or .aioson/context/prd-{slug}.md',
      '.aioson/context/implementation-plan.md or .aioson/context/implementation-plan-{slug}.md (when present)'
    ],
    output: 'bounded interaction decision to Product or Planner + optional dossier entry'
  },
  {
    id: 'pm',
    displayName: 'PM',
    description: 'Optional prioritization, dependency, and rollout advisor (all sizes)',
    command: '@pm',
    path: '.aioson/agents/pm.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/prd.md or .aioson/context/prd-{slug}.md',
      '.aioson/context/implementation-plan.md or .aioson/context/implementation-plan-{slug}.md (when present)'
    ],
    output: 'bounded recommendation to Product or Planner + optional dossier entry'
  },
  {
    id: 'dev',
    displayName: 'Dev',
    description: 'Feature implementation (any stack)',
    command: '@dev',
    path: '.aioson/agents/dev.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/prd.md or .aioson/context/prd-{slug}.md',
      '.aioson/context/implementation-plan.md or .aioson/context/implementation-plan-{slug}.md',
      '.aioson/briefings/{slug}/prototype.html + prototype-manifest.md (when referenced by the PRD)'
    ],
    output: 'code changes'
  },
  {
    id: 'pentester',
    displayName: 'Pentester',
    description: 'Evidence-driven adversarial review, bounded hardening, and localized security coverage reports',
    command: '@pentester',
    path: '.aioson/agents/pentester.md',
    flags: [
      { name: 'mode', value: 'framework_target|app_target', description: 'Target mode for security review' },
      { name: 'feature', value: '<slug>', description: 'Feature slug (required for app_target)' },
      { name: 'scope', value: '<scope>', description: 'Target scope (required for app_target)' },
      { name: 'scope-mode', value: 'feature|simple-plan|paths|routes|project', description: 'What to review; asked when not supplied, and feature/simple-plan without a slug lists the candidates' },
      { name: 'paths', value: '<paths>', description: 'Explicit folders/files for --scope-mode=paths' },
      { name: 'routes', value: '<routes>', description: 'Explicit local routes/URL for --scope-mode=routes' },
      { name: 'report', value: 'full|none', description: 'HTML report bundle or economy mode without it (default full)' }
    ],
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/prd-{slug}.md (active feature)',
      '.aioson/context/implementation-plan-{slug}.md (approved paths and risk surfaces)'
    ],
    output: '.aioson/context/security-findings-{slug}.json + .aioson/pentester/{run_id}/relatorios/*.html when --report=full'
  },
  {
    id: 'qa',
    displayName: 'QA',
    description: 'Proportional delivery review with bounded focused verification (all sizes)',
    command: '@qa',
    path: '.aioson/agents/qa.md',
    dependsOn: [
      '.aioson/context/prd.md or .aioson/context/prd-{slug}.md',
      '.aioson/context/implementation-plan.md or .aioson/context/implementation-plan-{slug}.md'
    ],
    output: '.aioson/context/qa-report-{slug}.md'
  },
  {
    id: 'quality',
    displayName: 'Quality',
    description: 'Optional engineering quality assessment, static analysis and reproducible evaluations',
    command: '@quality',
    path: '.aioson/agents/quality.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/context/quality-review-{target}.md + .aioson/runtime/quality/'
  },
  {
    id: 'validator',
    displayName: 'Validator',
    description: 'Technical validation against success contract',
    command: '@validator',
    path: '.aioson/agents/validator.md',
    dependsOn: [
      '.aioson/plans/{slug}/harness-contract.json',
      '.aioson/plans/{slug}/progress.json'
    ],
    output: '.aioson/plans/{slug}/last-validator-output.json'
  },
  {
    id: 'shakedown',
    displayName: 'Shakedown',
    description: 'Spec-independent post-delivery completeness walkthrough and bug hunt (opt-in, all sizes)',
    command: '@shakedown',
    path: '.aioson/agents/shakedown.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/context/shakedown-{slug}.md punch list (bug / incomplete / polish + coverage proof)'
  },
  {
    id: 'tester',
    displayName: 'Tester',
    description: 'Systematic test engineering for implemented apps (all sizes)',
    command: '@tester',
    path: '.aioson/agents/tester.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/prd-{slug}.md (active feature)',
      '.aioson/context/implementation-plan-{slug}.md (approved controls and paths)'
    ],
    output: '.aioson/context/test-report-{slug}.md'
  },
  {
    id: 'orchestrator',
    displayName: 'Orchestrator',
    description: 'Optional coordination for genuinely parallel or cross-cutting execution (all sizes)',
    command: '@orchestrator',
    path: '.aioson/agents/orchestrator.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/prd.md or .aioson/context/prd-{slug}.md',
      '.aioson/context/implementation-plan.md or implementation-plan-{slug}.md'
    ],
    output: 'bounded lane ownership and merge order + optional dossier entry'
  },
  {
    id: 'squad',
    displayName: 'Squad',
    description: 'Squad assembly and management',
    command: '@squad',
    path: '.aioson/agents/squad.md',
    dependsOn: [],
    output:
      '.aioson/squads/{slug}/squad.manifest.json + .aioson/squads/{slug}/squad.md + .aioson/squads/{slug}/agents/ + .aioson/squads/{slug}/workers/ + .aioson/squads/{slug}/workflows/ + .aioson/squads/{slug}/checklists/ + .aioson/squads/{slug}/skills/ + .aioson/squads/{slug}/templates/ + .aioson/squads/{slug}/docs/ + output/{slug}/{session-id}.html + output/{slug}/{content-key}/content.json + output/{slug}/{content-key}/index.html + output/{slug}/latest.html + aioson-logs/{slug}/ + media/{slug}/'
  },
  {
    id: 'orache',
    displayName: 'Orache',
    description: 'Domain investigation and strategic research',
    command: '@orache',
    path: '.aioson/agents/orache.md',
    dependsOn: [],
    output: 'squad-searches/{squad-slug}/investigation-{date}.md or squad-searches/standalone/{domain-slug}-{date}.md'
  },
  {
    id: 'genome',
    displayName: 'Genome',
    description: 'Domain genome creation and application',
    command: '@genome',
    path: '.aioson/agents/genome.md',
    dependsOn: [],
    output: '.aioson/genomes/[slug].md + .aioson/genomes/[slug].meta.json + optional binding in .aioson/squads/{slug}/squad.md or .aioson/squads/{slug}/squad.manifest.json'
  },
  {
    id: 'design-hybrid-forge',
    displayName: 'Design Hybrid Forge',
    description: 'Generate a design skill from two visual parents, external sources, or an original from-scratch brief',
    command: '@design-hybrid-forge',
    path: '.aioson/agents/design-hybrid-forge.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/installed-skills/{hybrid-slug}/SKILL.md + .aioson/installed-skills/{hybrid-slug}/references/ + .aioson/installed-skills/{hybrid-slug}/previews/ + .aioson/installed-skills/{hybrid-slug}/.skill-meta.json'
  },
  {
    id: 'site-forge',
    displayName: 'Site Forge',
    description: 'Clone, extract, and forge sites and design skills from any URL',
    command: '@site-forge',
    path: '.aioson/agents/site-forge.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: 'src/components/*.tsx + src/app/page.tsx + docs/research/{hostname}/ + public/images/{hostname}/'
  },
  {
    id: 'benchmark',
    displayName: 'Benchmark',
    description: 'Conduct one measured AIOSON traversal: route detection, unattended agent chain, honest run artifacts',
    command: '@benchmark',
    path: '.aioson/agents/benchmark.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: 'runnable app/game + benchmark-result.json + report.md in the assigned run root'
  },
  {
    id: 'forge-run',
    displayName: 'Forge Run',
    description: 'Compile and run the Lane B workflow harness for a MEDIUM feature',
    command: '@forge-run',
    path: '.aioson/agents/forge-run.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/plans/{slug}/forge-run.workflow.js + workflow run verdict (stops before feature:close)'
  },
  {
    id: 'neo',
    displayName: 'Neo',
    description: 'System router: see the full picture, get guided to the right agent',
    command: '@neo',
    path: '.aioson/agents/neo.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: 'routing decision + agent handoff'
  },
  {
    id: 'help',
    displayName: 'Help',
    description: 'Beginner-friendly guide to AIOSON concepts, workflows, commands, and next steps',
    command: '@help',
    path: '.aioson/agents/help.md',
    dependsOn: [],
    output: 'beginner-friendly explanation in chat + one safe next action'
  },
  {
    id: 'sheldon',
    displayName: 'Sheldon',
    description: 'PRD quality review and pre-implementation enrichment',
    command: '@sheldon',
    path: '.aioson/agents/sheldon.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/prd.md or .aioson/context/prd-{slug}.md',
      '.aioson/briefings/{slug}/prototype.html + prototype-manifest.md (when present)'
    ],
    output: 'mandatory independent in-place PRD review, sealed by sheldon_review: approved and a current hash-bound PASS'
  },
  {
    id: 'planner',
    displayName: 'Planner',
    description: 'Executable vertical implementation planning from the approved PRD',
    command: '@planner',
    path: '.aioson/agents/planner.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/prd.md or .aioson/context/prd-{slug}.md',
      '.aioson/briefings/{slug}/prototype.html + prototype-manifest.md (when referenced by the PRD)'
    ],
    output: '.aioson/context/implementation-plan.md or .aioson/context/implementation-plan-{slug}.md'
  },
  {
    id: 'committer',
    displayName: 'Committer',
    description: 'Professional Git commit generation from changes and context',
    command: '@committer',
    path: '.aioson/agents/committer.md',
    dependsOn: [],
    output: 'git commit(s)'
  },
  {
    id: 'copywriter',
    displayName: 'Copywriter',
    description: 'Conversion-focused marketing copy',
    command: '@copywriter',
    path: '.aioson/agents/copywriter.md',
    dependsOn: [],
    output: 'marketing copy + content assets'
  },
  {
    id: 'briefing',
    displayName: 'Briefing',
    description: 'Pre-production briefings and planning',
    command: '@briefing',
    path: '.aioson/agents/briefing.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/briefings/{slug}/'
  },
  {
    id: 'refiner',
    displayName: 'Refiner',
    description: 'Interactive refinement of briefing artifacts before Product PRD generation',
    command: '@refiner',
    path: '.aioson/agents/refiner.md',
    // Renamed from `briefing-refiner` (v1.61). Unlike `aliases` (live stubs
    // with their own file, e.g. `pair`), a legacy id ships NO file: it stays
    // resolvable everywhere an agent id is consumed — CLI flags, client-owned
    // rules frontmatter, brains, dossier authors — so projects mid-flight keep
    // routing, and `aioson update` removes the files the old name left behind.
    legacyIds: ['briefing-refiner'],
    dependsOn: ['.aioson/context/project.context.md', '.aioson/briefings/config.md'],
    output: '.aioson/briefings/{slug}/review.html + refinement-feedback.json + refinement-report.md'
  },
  {
    id: 'profiler-researcher',
    displayName: 'Profiler Researcher',
    description: 'Clone profiler: research phase',
    command: '@profiler-researcher',
    path: '.aioson/agents/profiler-researcher.md',
    dependsOn: [],
    output: '.aioson/profiler-reports/{person-slug}/research-report.md'
  },
  {
    id: 'profiler-enricher',
    displayName: 'Profiler Enricher',
    description: 'Clone profiler: enrichment phase',
    command: '@profiler-enricher',
    path: '.aioson/agents/profiler-enricher.md',
    dependsOn: ['.aioson/profiler-reports/{person-slug}/research-report.md'],
    output: '.aioson/profiler-reports/{person-slug}/enriched-profile.md'
  },
  {
    id: 'profiler-forge',
    displayName: 'Profiler Forge',
    description: 'Clone profiler: forge and validate',
    command: '@profiler-forge',
    path: '.aioson/agents/profiler-forge.md',
    dependsOn: ['.aioson/profiler-reports/{person-slug}/enriched-profile.md'],
    output: '.aioson/genomes/{person-slug}-{domain-slug}.md + .aioson/genomes/{person-slug}-{domain-slug}.meta.json + .aioson/advisors/{person-slug}-advisor.md'
  }
];

module.exports = {
  MANAGED_FILES,
  REQUIRED_FILES,
  CONTEXT_REQUIRED_FIELDS,
  CONTEXT_ALLOWED_CLASSIFICATIONS,
  CONTEXT_ALLOWED_PROJECT_TYPES,
  CONTEXT_ALLOWED_PROFILES,
  AGENT_DEFINITIONS
};
