'use strict';

const MANAGED_FILES = [
  'CLAUDE.md',
  'AGENTS.md',
  'OPENCODE.md',
  '.aioson/config.md',
  '.aioson/agents/setup.md',
  '.aioson/agents/discovery-design-doc.md',
  '.aioson/agents/discover.md',
  '.aioson/agents/analyst.md',
  '.aioson/agents/scope-check.md',
  '.aioson/agents/architect.md',
  '.aioson/agents/ux-ui.md',
  '.aioson/agents/product.md',
  '.aioson/agents/deyvin.md',
  '.aioson/agents/pair.md',
  '.aioson/agents/pm.md',
  '.aioson/agents/sheldon.md',
  '.aioson/agents/dev.md',
  '.aioson/agents/qa.md',
  '.aioson/agents/validator.md',
  '.aioson/agents/tester.md',
  '.aioson/agents/orchestrator.md',
  '.aioson/agents/pentester.md',
  '.aioson/agents/squad.md',
  '.aioson/agents/orache.md',
  '.aioson/agents/genome.md',
  '.aioson/agents/neo.md',
  '.aioson/agents/design-hybrid-forge.md',
  '.aioson/agents/site-forge.md',
  '.aioson/agents/profiler-researcher.md',
  '.aioson/agents/profiler-enricher.md',
  '.aioson/agents/profiler-forge.md',
  '.aioson/agents/committer.md',
  '.aioson/agents/copywriter.md',
  '.aioson/agents/briefing.md',
  '.aioson/agents/briefing-refiner.md',
  '.aioson/agents/forge-run.md',
  '.aioson/docs/squad/package-contract.md',
  '.aioson/docs/squad/creation-flow.md',
  '.aioson/docs/squad/research-loop.md',
  '.aioson/docs/squad/quality-lens.md',
  '.aioson/docs/squad/workflow-quality.md',
  '.aioson/docs/squad/content-output.md',
  '.aioson/docs/squad/session-operations.md',
  '.aioson/docs/squad/genome-bindings.md',
  '.aioson/docs/feature-expansion-taxonomy.md',
  '.aioson/docs/prototype-contract.md',
  '.aioson/docs/product/conversation-playbook.md',
  '.aioson/docs/product/research-loop.md',
  '.aioson/docs/product/quality-lens.md',
  '.aioson/docs/product/prd-contract.md',
  '.aioson/docs/deyvin/continuity-recovery.md',
  '.aioson/docs/deyvin/pair-execution.md',
  '.aioson/docs/deyvin/runtime-handoffs.md',
  '.aioson/docs/deyvin/debugging-escalation.md',
  '.aioson/docs/handoff-persistence.md',
  '.aioson/docs/integrations/dashboard-app-form-publish-mapping.md',
  '.aioson/docs/play/README.md',
  '.aioson/docs/play/agent-usage-guide.md',
  '.aioson/docs/play/app-compatibility-guide.md',
  '.aioson/docs/play/auth-services-and-testing.md',
  '.aioson/docs/play/llm-data-and-bindings.md',
  '.aioson/docs/play/manifest-and-runtime.md',
  '.aioson/docs/play/source-map.md',
  '.aioson/docs/sheldon/research-loop.md',
  '.aioson/docs/sheldon/web-intelligence.md',
  '.aioson/docs/sheldon/quality-lens.md',
  '.aioson/docs/sheldon/enrichment-paths.md',
  '.aioson/docs/sheldon/harness-contract.md',
  '.aioson/docs/dev/stack-conventions.md',
  '.aioson/docs/dev/execution-discipline.md',
  '.aioson/docs/dev/simple-plan-lane.md',
  '.aioson/docs/quality/code-health-analysis.md',
  '.aioson/skills/process/decision-presentation/SKILL.md',
  '.aioson/skills/process/decision-presentation/references/jargon-map.en.yaml',
  '.aioson/skills/process/decision-presentation/references/jargon-map.pt-BR.yaml',
  '.aioson/skills/process/prompt-sharpener/SKILL.md',
  '.aioson/skills/process/prompt-sharpener/references/prompt-diagnostics.md',
  '.aioson/skills/process/prompt-sharpener/agents/openai.yaml',
  '.aioson/skills/process/briefing-expansion-scout/SKILL.md',
  '.aioson/skills/process/product-scope-expansion/SKILL.md',
  '.aioson/skills/process/sheldon-expansion-audit/SKILL.md',
  '.aioson/skills/process/prototype-forge/SKILL.md',
  '.aioson/skills/static/laravel-conventions.md',
  '.aioson/skills/static/tall-stack-patterns.md',
  '.aioson/skills/static/jetstream-setup.md',
  '.aioson/skills/static/rails-conventions.md',
  '.aioson/skills/static/node-express-patterns.md',
  '.aioson/skills/static/node-typescript-patterns.md',
  '.aioson/skills/static/nextjs-patterns.md',
  '.aioson/skills/static/ui-ux-modern.md',
  '.aioson/skills/static/landing-page-forge.md',
  '.aioson/skills/static/landing-page-deploy.md',
  '.aioson/skills/marketing/vsl-craft.md',
  '.aioson/skills/marketing/references/one-belief.md',
  '.aioson/skills/marketing/references/five-acts.md',
  '.aioson/skills/marketing/references/fascinations.md',
  '.aioson/skills/marketing/references/offer-structure.md',
  '.aioson/skills/marketing/references/pms-research.md',
  '.aioson/skills/marketing/references/patterns.md',
  '.aioson/skills/marketing/references/anti-patterns.md',
  '.aioson/skills/marketing/references/market-intelligence.md',
  '.aioson/genomes/copywriting.md',
  '.aioson/skills/static/web3-ethereum-patterns.md',
  '.aioson/skills/static/web3-solana-patterns.md',
  '.aioson/skills/static/web3-cardano-patterns.md',
  '.aioson/skills/static/web3-security-checklist.md',
  '.aioson/skills/static/git-conventions.md',
  '.aioson/skills/design/aurora-command-ui/SKILL.md',
  '.aioson/skills/design/aurora-command-ui/references/art-direction.md',
  '.aioson/skills/design/aurora-command-ui/references/components.md',
  '.aioson/skills/design/aurora-command-ui/references/dashboards.md',
  '.aioson/skills/design/aurora-command-ui/references/design-tokens.md',
  '.aioson/skills/design/aurora-command-ui/references/motion.md',
  '.aioson/skills/design/aurora-command-ui/references/patterns.md',
  '.aioson/skills/design/aurora-command-ui/references/websites.md',
  '.aioson/skills/design/bold-editorial-ui/SKILL.md',
  '.aioson/skills/design/bold-editorial-ui/references/art-direction.md',
  '.aioson/skills/design/bold-editorial-ui/references/components.md',
  '.aioson/skills/design/bold-editorial-ui/references/dashboards.md',
  '.aioson/skills/design/bold-editorial-ui/references/design-tokens.md',
  '.aioson/skills/design/bold-editorial-ui/references/motion.md',
  '.aioson/skills/design/bold-editorial-ui/references/patterns.md',
  '.aioson/skills/design/bold-editorial-ui/references/websites.md',
  '.aioson/skills/design/clean-saas-ui/SKILL.md',
  '.aioson/skills/design/clean-saas-ui/references/art-direction.md',
  '.aioson/skills/design/clean-saas-ui/references/components.md',
  '.aioson/skills/design/clean-saas-ui/references/dashboards.md',
  '.aioson/skills/design/clean-saas-ui/references/design-tokens.md',
  '.aioson/skills/design/clean-saas-ui/references/motion.md',
  '.aioson/skills/design/clean-saas-ui/references/patterns.md',
  '.aioson/skills/design/clean-saas-ui/references/websites.md',
  '.aioson/skills/design/cognitive-core-ui/SKILL.md',
  '.aioson/skills/design/cognitive-core-ui/references/art-direction.md',
  '.aioson/skills/design/cognitive-core-ui/references/components.md',
  '.aioson/skills/design/cognitive-core-ui/references/dashboards.md',
  '.aioson/skills/design/cognitive-core-ui/references/design-tokens.md',
  '.aioson/skills/design/cognitive-core-ui/references/motion.md',
  '.aioson/skills/design/cognitive-core-ui/references/patterns.md',
  '.aioson/skills/design/cognitive-core-ui/references/websites.md',
  '.aioson/skills/design/glassmorphism-ui/SKILL.md',
  '.aioson/skills/design/glassmorphism-ui/references/art-direction.md',
  '.aioson/skills/design/glassmorphism-ui/references/components.md',
  '.aioson/skills/design/glassmorphism-ui/references/dashboards.md',
  '.aioson/skills/design/glassmorphism-ui/references/design-tokens.md',
  '.aioson/skills/design/glassmorphism-ui/references/motion.md',
  '.aioson/skills/design/glassmorphism-ui/references/patterns.md',
  '.aioson/skills/design/glassmorphism-ui/references/websites.md',
  '.aioson/skills/design/interface-design/SKILL.md',
  '.aioson/skills/design/interface-design/references/components-and-states.md',
  '.aioson/skills/design/interface-design/references/design-directions.md',
  '.aioson/skills/design/interface-design/references/handoff-and-quality.md',
  '.aioson/skills/design/interface-design/references/intent-and-domain.md',
  '.aioson/skills/design/interface-design/references/tokens-and-depth.md',
  '.aioson/skills/design/neo-brutalist-ui/SKILL.md',
  '.aioson/skills/design/neo-brutalist-ui/references/art-direction.md',
  '.aioson/skills/design/neo-brutalist-ui/references/components.md',
  '.aioson/skills/design/neo-brutalist-ui/references/dashboards.md',
  '.aioson/skills/design/neo-brutalist-ui/references/design-tokens.md',
  '.aioson/skills/design/neo-brutalist-ui/references/motion.md',
  '.aioson/skills/design/neo-brutalist-ui/references/patterns.md',
  '.aioson/skills/design/neo-brutalist-ui/references/websites.md',
  '.aioson/skills/design/premium-command-center-ui/SKILL.md',
  '.aioson/skills/design/premium-command-center-ui/references/operations.md',
  '.aioson/skills/design/premium-command-center-ui/references/patterns.md',
  '.aioson/skills/design/premium-command-center-ui/references/validation.md',
  '.aioson/skills/design/premium-command-center-ui/references/visual-system.md',
  '.aioson/skills/design/pt.squarespace.com/.skill-meta.json',
  '.aioson/skills/design/pt.squarespace.com/SKILL.md',
  '.aioson/skills/design/pt.squarespace.com/references/components.md',
  '.aioson/skills/design/pt.squarespace.com/references/design-tokens.md',
  '.aioson/skills/design/pt.squarespace.com/references/motion.md',
  '.aioson/skills/design/pt.squarespace.com/references/patterns.md',
  '.aioson/skills/design/pt.squarespace.com/references/websites.md',
  '.aioson/skills/design/warm-craft-ui/SKILL.md',
  '.aioson/skills/design/warm-craft-ui/references/art-direction.md',
  '.aioson/skills/design/warm-craft-ui/references/components.md',
  '.aioson/skills/design/warm-craft-ui/references/dashboards.md',
  '.aioson/skills/design/warm-craft-ui/references/design-tokens.md',
  '.aioson/skills/design/warm-craft-ui/references/motion.md',
  '.aioson/skills/design/warm-craft-ui/references/patterns.md',
  '.aioson/skills/design/warm-craft-ui/references/websites.md',
  '.aioson/skills/dynamic/laravel-docs.md',
  '.aioson/skills/dynamic/flux-ui-docs.md',
  '.aioson/skills/dynamic/npm-packages.md',
  '.aioson/skills/dynamic/ethereum-docs.md',
  '.aioson/skills/dynamic/solana-docs.md',
  '.aioson/skills/dynamic/cardano-docs.md',
  '.aioson/mcp/servers.md',
  '.aioson/schemas/genome.schema.json',
  '.aioson/schemas/genome-meta.schema.json',
  '.aioson/schemas/squad-manifest.schema.json',
  '.aioson/schemas/squad-blueprint.schema.json',
  '.aioson/schemas/readiness.schema.json',
  '.aioson/schemas/content-blueprint.schema.json',
  '.aioson/schemas/genome.schema.json',
  '.aioson/schemas/genome-meta.schema.json',
  '.aioson/tasks/squad-design.md',
  '.aioson/tasks/squad-create.md',
  '.aioson/tasks/squad-validate.md',
  '.aioson/tasks/squad-analyze.md',
  '.aioson/tasks/squad-extend.md',
  '.aioson/tasks/squad-export.md',
  '.aioson/tasks/squad-repair.md',
  '.aioson/tasks/squad-pipeline.md',
  '.aioson/tasks/squad-learning-review.md',
  '.aioson/profiler-reports/.gitkeep',
  '.aioson/advisors/.gitkeep'
];

const REQUIRED_FILES = [
  'CLAUDE.md',
  'AGENTS.md',
  'OPENCODE.md',
  '.claude/commands/aioson/agent/setup.md',
  '.claude/commands/aioson/agent/discover.md',
  '.claude/commands/aioson/agent/dev.md',
  '.claude/commands/aioson/agent/qa.md',
  '.aioson/config.md',
  '.aioson/agents/setup.md',
  '.aioson/agents/discovery-design-doc.md',
  '.aioson/agents/discover.md',
  '.aioson/agents/analyst.md',
  '.aioson/agents/ux-ui.md',
  '.aioson/agents/dev.md',
  '.aioson/context/.gitkeep'
];

const CONTEXT_REQUIRED_FIELDS = [
  'project_name',
  'project_type',
  'profile',
  'framework',
  'framework_installed',
  'classification',
  'conversation_language',
  'aioson_version'
];

const CONTEXT_ALLOWED_CLASSIFICATIONS = ['MICRO', 'SMALL', 'MEDIUM'];
const CONTEXT_ALLOWED_PROJECT_TYPES = ['web_app', 'api', 'site', 'script', 'dapp', 'desktop_app'];
const CONTEXT_ALLOWED_PROFILES = ['developer', 'creator', 'team'];

const AGENT_DEFINITIONS = [
  {
    id: 'setup',
    displayName: 'Setup',
    description: 'Project onboarding and context setup',
    command: '@setup',
    path: '.aioson/agents/setup.md',
    dependsOn: [],
    output: '.aioson/context/project.context.md'
  },
  {
    id: 'discovery-design-doc',
    displayName: 'Discovery/Design Doc',
    description: 'Discovery and design doc generation',
    command: '@discovery-design-doc',
    path: '.aioson/agents/discovery-design-doc.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/context/design-doc*.md + .aioson/context/readiness*.md'
  },
  {
    id: 'discover',
    displayName: 'Discover',
    description: 'Semantic knowledge discovery and bootstrap cache generation',
    command: '@discover',
    path: '.aioson/agents/discover.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/context/bootstrap/what-is.md + .aioson/context/bootstrap/how-it-works.md + .aioson/context/bootstrap/what-it-does.md + .aioson/context/bootstrap/current-state.md'
  },
  {
    id: 'product',
    displayName: 'Product',
    description: 'Product vision, PRD and feature scoping',
    command: '@product',
    path: '.aioson/agents/product.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/context/prd.md or .aioson/context/prd-{slug}.md (PRD base)'
  },
  {
    id: 'deyvin',
    displayName: 'Deyvin',
    description: 'Pair programming partner for continuity sessions',
    command: '@deyvin',
    path: '.aioson/agents/deyvin.md',
    aliases: ['pair'],
    dependsOn: ['.aioson/context/project.context.md'],
    output: 'small code changes + continuity notes in spec.md + runtime logs/tasks'
  },
  {
    id: 'analyst',
    displayName: 'Analyst',
    description: 'Domain discovery and entity mapping (SMALL/MEDIUM)',
    command: '@analyst',
    path: '.aioson/agents/analyst.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/context/discovery.md or .aioson/context/requirements-{slug}.md + .aioson/context/spec-{slug}.md'
  },
  {
    id: 'scope-check',
    displayName: 'Scope Check',
    description: 'Scope alignment before development and optional post-dev drift checks',
    command: '@scope-check',
    path: '.aioson/agents/scope-check.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/prd.md or .aioson/context/prd-{slug}.md',
      '.aioson/context/discovery.md or .aioson/context/requirements-{slug}.md + .aioson/context/spec-{slug}.md'
    ],
    output: '.aioson/context/scope-check.md or .aioson/context/scope-check-{slug}.md'
  },
  {
    id: 'architect',
    displayName: 'Architect',
    description: 'Project structure and technical decisions (SMALL/MEDIUM)',
    command: '@architect',
    path: '.aioson/agents/architect.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/discovery.md or .aioson/context/requirements-{slug}.md + .aioson/context/spec-{slug}.md'
    ],
    output: '.aioson/context/architecture.md'
  },
  {
    id: 'ux-ui',
    displayName: 'UI/UX',
    description: 'UI/UX design system and component spec (SMALL/MEDIUM)',
    command: '@ux-ui',
    path: '.aioson/agents/ux-ui.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/prd.md or .aioson/context/prd-{slug}.md',
      '.aioson/context/discovery.md',
      '.aioson/context/architecture.md'
    ],
    output: '.aioson/context/ui-spec-{slug}.md (project mode: .aioson/context/ui-spec.md) + Visual identity enrichment in prd.md or prd-{slug}.md'
  },
  {
    id: 'pm',
    displayName: 'PM',
    description: 'Backlog and user stories (MEDIUM only)',
    command: '@pm',
    path: '.aioson/agents/pm.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/prd.md or .aioson/context/prd-{slug}.md',
      '.aioson/context/requirements-{slug}.md + .aioson/context/spec-{slug}.md (feature mode)',
      '.aioson/context/discovery.md',
      '.aioson/context/architecture.md',
      '.aioson/context/design-doc-{slug}.md + .aioson/context/readiness-{slug}.md (feature mode, when present)',
      '.aioson/context/ui-spec.md (when present)'
    ],
    output: '.aioson/context/prd.md or prd-{slug}.md (enriched with acceptance criteria) + .aioson/context/implementation-plan-{slug}.md for MEDIUM features'
  },
  {
    id: 'dev',
    displayName: 'Dev',
    description: 'Feature implementation (any stack)',
    command: '@dev',
    path: '.aioson/agents/dev.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/discovery.md',
      '.aioson/context/architecture.md'
    ],
    output: 'code changes'
  },
  {
    id: 'pentester',
    displayName: 'Pentester',
    description: 'Adversarial security review and threat-surface mapping',
    command: '@pentester',
    path: '.aioson/agents/pentester.md',
    flags: [
      { name: 'mode', value: 'framework_target|app_target', description: 'Target mode for security review' },
      { name: 'feature', value: '<slug>', description: 'Feature slug (required for app_target)' },
      { name: 'scope', value: '<scope>', description: 'Target scope (required for app_target)' }
    ],
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/spec-{slug}.md (active feature)'
    ],
    output: '.aioson/context/security-findings-{slug}.json'
  },
  {
    id: 'qa',
    displayName: 'QA',
    description: 'Risk-first review and test generation (SMALL/MEDIUM)',
    command: '@qa',
    path: '.aioson/agents/qa.md',
    dependsOn: ['.aioson/context/discovery.md'],
    output: 'QA report'
  },
  {
    id: 'validator',
    displayName: 'Validator',
    description: 'Technical validation against success contract',
    command: '@validator',
    path: '.aioson/agents/validator.md',
    dependsOn: [
      '.aioson/plans/{slug}/harness-contract.json',
      '.aioson/plans/{slug}/progress.json'
    ],
    output: '.aioson/plans/{slug}/last-validator-output.json'
  },
  {
    id: 'tester',
    displayName: 'Tester',
    description: 'Systematic test engineering for implemented apps (all sizes)',
    command: '@tester',
    path: '.aioson/agents/tester.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/context/test-inventory-{slug}.md + .aioson/context/test-plan-{slug}.md (project mode: bare names)'
  },
  {
    id: 'orchestrator',
    displayName: 'Orchestrator',
    description: 'Session protocol and parallel execution (MEDIUM)',
    command: '@orchestrator',
    path: '.aioson/agents/orchestrator.md',
    dependsOn: [
      '.aioson/context/project.context.md',
      '.aioson/context/discovery.md',
      '.aioson/context/architecture.md',
      '.aioson/context/prd.md or .aioson/context/prd-{slug}.md',
      '.aioson/context/ui-spec.md (when present)',
      '.aioson/context/implementation-plan.md or implementation-plan-{slug}.md (when present)'
    ],
    output: '.aioson/context/parallel/*.status.md'
  },
  {
    id: 'squad',
    displayName: 'Squad',
    description: 'Squad assembly and management',
    command: '@squad',
    path: '.aioson/agents/squad.md',
    dependsOn: [],
    output:
      '.aioson/squads/{slug}/squad.manifest.json + .aioson/squads/{slug}/squad.md + .aioson/squads/{slug}/agents/ + .aioson/squads/{slug}/workers/ + .aioson/squads/{slug}/workflows/ + .aioson/squads/{slug}/checklists/ + .aioson/squads/{slug}/skills/ + .aioson/squads/{slug}/templates/ + .aioson/squads/{slug}/docs/ + output/{slug}/{session-id}.html + output/{slug}/{content-key}/content.json + output/{slug}/{content-key}/index.html + output/{slug}/latest.html + aioson-logs/{slug}/ + media/{slug}/'
  },
  {
    id: 'orache',
    displayName: 'Orache',
    description: 'Domain investigation and strategic research',
    command: '@orache',
    path: '.aioson/agents/orache.md',
    dependsOn: [],
    output: 'squad-searches/{squad-slug}/investigation-{date}.md or squad-searches/standalone/{domain-slug}-{date}.md'
  },
  {
    id: 'genome',
    displayName: 'Genome',
    description: 'Domain genome creation and application',
    command: '@genome',
    path: '.aioson/agents/genome.md',
    dependsOn: [],
    output: '.aioson/genomes/[slug].md + .aioson/genomes/[slug].meta.json + optional binding in .aioson/squads/{slug}/squad.md or .aioson/squads/{slug}/squad.manifest.json'
  },
  {
    id: 'design-hybrid-forge',
    displayName: 'Design Hybrid Forge',
    description: 'Generate hybrid design skill from two visual parents',
    command: '@design-hybrid-forge',
    path: '.aioson/agents/design-hybrid-forge.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/installed-skills/{hybrid-slug}/SKILL.md + .aioson/installed-skills/{hybrid-slug}/references/ + .aioson/installed-skills/{hybrid-slug}/previews/ + .aioson/installed-skills/{hybrid-slug}/.skill-meta.json'
  },
  {
    id: 'site-forge',
    displayName: 'Site Forge',
    description: 'Clone, extract, and forge sites and design skills from any URL',
    command: '@site-forge',
    path: '.aioson/agents/site-forge.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: 'src/components/*.tsx + src/app/page.tsx + docs/research/{hostname}/ + public/images/{hostname}/'
  },
  {
    id: 'forge-run',
    displayName: 'Forge Run',
    description: 'Compile and run the Lane B workflow harness for a MEDIUM feature',
    command: '@forge-run',
    path: '.aioson/agents/forge-run.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/plans/{slug}/forge-run.workflow.js + workflow run verdict (stops before feature:close)'
  },
  {
    id: 'neo',
    displayName: 'Neo',
    description: 'System router: see the full picture, get guided to the right agent',
    command: '@neo',
    path: '.aioson/agents/neo.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: 'routing decision + agent handoff'
  },
  {
    id: 'sheldon',
    displayName: 'Sheldon',
    description: 'PRD quality review and pre-implementation enrichment',
    command: '@sheldon',
    path: '.aioson/agents/sheldon.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: 'enriched PRD or phased execution plan (+ sheldon-validation-{slug}.md readiness gate on MEDIUM)'
  },
  {
    id: 'committer',
    displayName: 'Committer',
    description: 'Professional Git commit generation from changes and context',
    command: '@committer',
    path: '.aioson/agents/committer.md',
    dependsOn: [],
    output: 'git commit(s)'
  },
  {
    id: 'copywriter',
    displayName: 'Copywriter',
    description: 'Conversion-focused marketing copy',
    command: '@copywriter',
    path: '.aioson/agents/copywriter.md',
    dependsOn: [],
    output: 'marketing copy + content assets'
  },
  {
    id: 'briefing',
    displayName: 'Briefing',
    description: 'Pre-production briefings and planning',
    command: '@briefing',
    path: '.aioson/agents/briefing.md',
    dependsOn: ['.aioson/context/project.context.md'],
    output: '.aioson/briefings/{slug}/'
  },
  {
    id: 'briefing-refiner',
    displayName: 'Briefing Refiner',
    description: 'Interactive refinement of briefing artifacts before Product PRD generation',
    command: '@briefing-refiner',
    path: '.aioson/agents/briefing-refiner.md',
    dependsOn: ['.aioson/context/project.context.md', '.aioson/briefings/config.md'],
    output: '.aioson/briefings/{slug}/review.html + refinement-feedback.json + refinement-report.md'
  },
  {
    id: 'profiler-researcher',
    displayName: 'Profiler Researcher',
    description: 'Clone profiler: research phase',
    command: '@profiler-researcher',
    path: '.aioson/agents/profiler-researcher.md',
    dependsOn: [],
    output: '.aioson/profiler-reports/{person-slug}/research-report.md'
  },
  {
    id: 'profiler-enricher',
    displayName: 'Profiler Enricher',
    description: 'Clone profiler: enrichment phase',
    command: '@profiler-enricher',
    path: '.aioson/agents/profiler-enricher.md',
    dependsOn: ['.aioson/profiler-reports/{person-slug}/research-report.md'],
    output: '.aioson/profiler-reports/{person-slug}/enriched-profile.md'
  },
  {
    id: 'profiler-forge',
    displayName: 'Profiler Forge',
    description: 'Clone profiler: forge and validate',
    command: '@profiler-forge',
    path: '.aioson/agents/profiler-forge.md',
    dependsOn: ['.aioson/profiler-reports/{person-slug}/enriched-profile.md'],
    output: '.aioson/genomes/{person-slug}-{domain-slug}.md + .aioson/genomes/{person-slug}-{domain-slug}.meta.json + .aioson/advisors/{person-slug}-advisor.md'
  }
];

module.exports = {
  MANAGED_FILES,
  REQUIRED_FILES,
  CONTEXT_REQUIRED_FIELDS,
  CONTEXT_ALLOWED_CLASSIFICATIONS,
  CONTEXT_ALLOWED_PROJECT_TYPES,
  CONTEXT_ALLOWED_PROFILES,
  AGENT_DEFINITIONS
};
